[book]
authors = ["TensorStack Authors"]
language = "zh-cn"
multilingual = false
src = "src"
title = "TensorStack AI 平台用户手册"

[output.html]
additional-css = ["theme/sidebar.css", "theme/custom.css"]
additional-js = ["theme/sidebar.js"]
curly-quotes = true

[preprocessor.tabulate]
command = "./util-tabulate.sh"

[preprocessor.embed]
command = "./util-embed.sh"

[preprocessor.releaselink]
command = "./util-releaselink.sh"
